[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm ci --no-cache']

[phases.build]
cmds = ['npm run clean', 'npm run check-node', 'npm ci --no-cache', 'npm run build']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'